/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file è usato per specificare quali progetti includere nella build.
 */

plugins {
    // Plugin per il download automatico di JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "GeoExplore"
include("app")
